library(tidyverse)
library(here)
library(kableExtra)
library(ggstatsplot)
library(patchwork)
library(survey)
library(qualtRics)
library(broom)
library(margins)
library(poLCA)
library(REdaS)
library(psych)
library(hrbrthemes)
library(GPArotation)
library(lavaan)
library(GGally)
library(questionr)
library(interactions)
set.seed(26111985)

fig_cols <- yarrr::piratepal(palette = "basel", 
                             trans = .2)
fig_cols <- as.character(fig_cols[1:9])
tmp <- as.character(yarrr::piratepal(palette = "pony", 
                        trans = .2)[5])
fig_cols <- c(fig_cols, tmp)

api_key_fn <- here("data/raw-private/qualtrics_api_key.txt")
API <- read_file(api_key_fn) %>% trimws()
