dl <- d |> 
  dplyr::select(-H19_9, -H19_12, -H19_13) |> 
  pivot_longer(cols = H19_1:H19_11,
               names_to = "groups",
               values_to = "sentiment") |>
  mutate(groups = recode(groups,
                       `H19_1` = "Multinationals",
                       `H19_2` = "Neo-Liberal Politicians",
                       `H19_3` = "Right-Wing Voters",
                       `H19_4` = "Left-Wing Voters",
                       `H19_5` = "Materialistic People",
                       `H19_6` = "Climate Activists",
                       `H19_7` = "Immigrants",
                       `H19_8` = "Living on Benefits",
                       `H19_10` = "Muslims",
                       `H19_11` = "Christians"),
         group_type = ifelse(groups == "Multinationals" & ideology == 0, "Out-group", NA),
         group_type = ifelse(groups == "Multinationals" & ideology == 1, "In-group", group_type),
         group_type = ifelse(groups == "Neo-Liberal Politicians" & ideology == 0, "Out-group", group_type),
         group_type = ifelse(groups == "Neo-Liberal Politicians" & ideology == 1, "In-group", group_type),
         group_type = ifelse(groups == "Right-Wing Voters" & ideology == 0, "Out-group", group_type),
         group_type = ifelse(groups == "Right-Wing Voters" & ideology == 1, "In-group", group_type),
         group_type = ifelse(groups == "Materialistic People" & ideology == 0, "Out-group", group_type),
         group_type = ifelse(groups == "Materialistic People" & ideology == 1, "In-group", group_type),
         group_type = ifelse(groups == "Climate Activists" & ideology == 1, "Out-group", group_type),
         group_type = ifelse(groups == "Climate Activists" & ideology == 0, "In-group", group_type),
         group_type = ifelse(groups == "Immigrants" & ideology == 1, "Out-group", group_type),
         group_type = ifelse(groups == "Immigrants" & ideology == 0, "In-group", group_type),
         group_type = ifelse(groups == "Left-Wing Voters" & ideology == 1, "Out-group", group_type),
         group_type = ifelse(groups == "Left-Wing Voters" & ideology == 0, "In-group", group_type),
         group_type = ifelse(groups == "Living on Benefits" & ideology == 1, "Out-group", group_type),
         group_type = ifelse(groups == "Living on Benefits" & ideology == 0, "In-group", group_type),
         group_type = ifelse(groups == "Muslims" & ideology == 1, "Out-group", group_type),
         group_type = ifelse(groups == "Muslims" & ideology == 0, "In-group", group_type),
         group_type = ifelse(groups == "Christians" & ideology == 1, "In-group", group_type),
         group_type = ifelse(groups == "Christians" & ideology == 0, "Out-group", group_type),
         treatment = ifelse(scapegoat == 0 & nostalgia == 0, "No Nostalgia, No Scapegoat", NA),
         treatment = ifelse(scapegoat == 0 & nostalgia == 1, "Nostalgia, No Scapegoat", treatment),
         treatment = ifelse(scapegoat == 1 & nostalgia == 0, "No Nostalgia, Scapegoat", treatment),
         treatment = ifelse(scapegoat == 1 & nostalgia == 1, "Nostalgia, Scapegoat", treatment),
         E2_2 = recode(E2_2,
                       `very conservative` = 1,
                       `consersative` = 2,
                       `center` = 3,
                       `progressive` = 4,
                       `very progressive` = 5))
  
